const data = {
  products: [
    {
      _id: "1",
      name: "Nike Slim Shirts",
      image: "/images/p1.jpeg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 22,
      description: "High Quality Product",
    },
    {
      _id: "2",
      name: "Adidas fit Shirts",
      image: "/images/p1.jpeg",
      price: 230,
      countInStock: 20,
      brand: "Adidas",
      rating: 4,
      numReviews: 10,
      description: "High Quality Product",
    },
    {
      _id: "3",
      name: "Puma Slim Shirts",
      image: "/images/p1.jpeg",
      price: 210,
      countInStock: 0,
      brand: "Puma",
      rating: 4.3,
      numReviews: 15,
      description: "High Quality Product",
    },
    {
      _id: "4",
      name: "Spykar Slim Shirts",
      image: "/images/p1.jpeg",
      price: 120,
      countInStock: 10,
      brand: "Spykar",
      rating: 4.5,
      numReviews: 30,
      description: "High Quality Product",
    },
    {
      _id: "5",
      name: "Mufti Slim Shirts",
      image: "/images/p1.jpeg",
      price: 400,
      countInStock: 15,
      brand: "Mufti",
      rating: 5,
      numReviews: 10,
      description: "High Quality Product",
    },
    {
      _id: "6",
      name: "Nike Slim Shirts",
      image: "/images/p1.jpeg",
      price: 120,
      countInStock: 30,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "High Quality Product",
    },
  ],
};

export default data;
